# -*- coding: utf-8 -*-
"""
Node Base Class Definition

Base class for all workflow nodes, defining basic node structure and interfaces.

Architecture Notes
------------------
- Parameter definitions uniformly use `Parameter` class from `src/core/parameter.py`
- `NodeParameter` is an alias for `Parameter`, maintaining backward compatibility
- This class is independent from `GraphNodeBase` in `src/core/graph_base.py`,
  because workflow nodes need port systems, execution states, and other specific features
"""

import logging
import uuid
from abc import ABC, abstractmethod
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple, Type

from .port import create_input_port, create_output_port, DataType, Port

# i18n (for user-visible strings like category names and validation errors)
from src.ui.i18n import tr_
# Import unified parameter class from core module
from src.core.parameter import Parameter as NodeParameter


logger = logging.getLogger(__name__)


class NodeCategory(Enum):
    """Node category"""
    DATA_SOURCE = "data_source"       # Data source
    PREPROCESSING = "preprocessing"   # Preprocessing
    AUGMENTATION = "augmentation"     # Data augmentation
    FEATURE = "feature"               # Feature extraction
    CONTROL = "control"               # Control flow
    TRAINING = "training"             # Training
    OUTPUT = "output"                 # Output
    
    @property
    def display_name(self) -> str:
        """Get display name"""
        names = {
            NodeCategory.DATA_SOURCE: tr_("Data source"),
            NodeCategory.PREPROCESSING: tr_("Preprocessing"),
            NodeCategory.AUGMENTATION: tr_("Data augmentation"),
            NodeCategory.FEATURE: tr_("Feature extraction"),
            NodeCategory.CONTROL: tr_("Data and flow"),
            NodeCategory.TRAINING: tr_("AI / Model"),
            NodeCategory.OUTPUT: tr_("Output / Visualization"),
        }
        return names.get(self, self.value)
    
    @property
    def color(self) -> str:
        """Get category color (Catppuccin Mocha)"""
        colors = {
            NodeCategory.DATA_SOURCE: "#89b4fa",    # Blue
            NodeCategory.PREPROCESSING: "#a6e3a1",  # Green
            NodeCategory.AUGMENTATION: "#f9e2af",   # Yellow
            NodeCategory.FEATURE: "#cba6f7",        # Purple
            NodeCategory.TRAINING: "#f38ba8",       # Red
            NodeCategory.CONTROL: "#94e2d5",        # Cyan
            NodeCategory.OUTPUT: "#fab387",         # Orange
        }
        return colors.get(self, "#cdd6f4")


class NodeState(Enum):
    """Node execution state"""
    IDLE = "idle"               # Idle
    WAITING = "waiting"         # Waiting for input
    RUNNING = "running"         # Executing
    COMPLETED = "completed"     # Completed
    ERROR = "error"             # Error
    SKIPPED = "skipped"         # Skipped


class BaseNode(ABC):
    """
    Node base class
    
    All workflow nodes must inherit from this class and implement the execute method.
    """
    
    # Class attributes - subclasses need to override
    node_type: str = "base_node"          # Node type identifier
    display_name: str = "Base Node"       # Display name
    category: NodeCategory = NodeCategory.DATA_SOURCE
    subcategory: str = ""                 # Optional subcategory for grouping
    description: str = ""                 # Node description
    icon: str = "📦"                       # Node icon (emoji or icon path)
    visible_in_palette: bool = True         # Legacy nodes may remain loadable but hidden
    subcategory_order: int = 100            # Lower values appear first in the palette
    palette_order: int = 100                # Lower values appear first within a group
    
    def __init__(self, node_id: str = None):
        """
        Initialize node
        
        Args:
            node_id: Node unique identifier, auto-generated by default
        """
        self.node_id = node_id or str(uuid.uuid4())[:8]
        self.inputs: Dict[str, Port] = {}
        self.outputs: Dict[str, Port] = {}
        self.parameters: Dict[str, NodeParameter] = {}
        self.parameter_values: Dict[str, Any] = {}
        
        # Node state
        self.state: NodeState = NodeState.IDLE
        self.error_message: str = ""
        
        # Position information (for UI)
        self.position: Tuple[float, float] = (0.0, 0.0)
        
        # Progress callback function: (progress: float, message: str, data: dict) -> None
        # Used for long-running nodes (e.g., training) to report progress
        self.progress_callback: Optional[callable] = None
        
        # Status message callback function: (message: str) -> None
        # Used to display key information in status bar
        self.status_callback: Optional[callable] = None
        
        # Initialize ports and parameters
        self._setup_ports()
        self._setup_parameters()
        self._init_parameter_values()
    
    @abstractmethod
    def _setup_ports(self):
        """
        Setup node input/output ports
        
        Subclasses must implement this method, using add_input and add_output to add ports.
        """
        pass
    
    def _setup_parameters(self):
        """
        Setup node parameters
        
        Subclasses can override this method to add parameters.
        """
        pass
    
    def _init_parameter_values(self):
        """Initialize parameter values to defaults"""
        for name, param in self.parameters.items():
            self.parameter_values[name] = param.default_value
    
    def add_input(
        self,
        name: str,
        data_type: DataType,
        display_name: str = None,
        required: bool = True,
        default_value: Any = None,
        description: str = ""
    ):
        """Add input port"""
        port = create_input_port(
            name=name,
            data_type=data_type,
            display_name=display_name,
            required=required,
            default_value=default_value,
            description=description
        )
        self.inputs[name] = port
    
    def add_output(
        self,
        name: str,
        data_type: DataType,
        display_name: str = None,
        description: str = ""
    ):
        """Add output port"""
        port = create_output_port(
            name=name,
            data_type=data_type,
            display_name=display_name,
            description=description
        )
        self.outputs[name] = port
    
    def add_parameter(
        self,
        name: str,
        param_type: str,
        default_value: Any,
        display_name: str = None,
        description: str = "",
        min_value: Any = None,
        max_value: Any = None,
        choices: List[Any] = None,
        file_filter: str = "",
        default_directory: str = ""
    ):
        """Add node parameter"""
        param = NodeParameter(
            name=name,
            display_name=display_name or name,
            param_type=param_type,
            default_value=default_value,
            description=description,
            min_value=min_value,
            max_value=max_value,
            choices=choices,
            file_filter=file_filter,
            default_directory=default_directory
        )
        self.parameters[name] = param
        self.parameter_values[name] = default_value
    
    def get_parameter(self, name: str) -> Any:
        """Get parameter value"""
        return self.parameter_values.get(name)
    
    def set_parameter(self, name: str, value: Any) -> Tuple[bool, str]:
        """
        Set parameter value
        
        Returns:
            (success, error_message)
        """
        if name not in self.parameters:
            return False, f"Unknown parameter: {name}"
        
        param = self.parameters[name]
        valid, msg = param.validate(value)
        if not valid:
            return False, msg
        
        self.parameter_values[name] = value
        return True, ""
    
    def get_input_data(self, port_name: str) -> Any:
        """Get data from input port"""
        if port_name not in self.inputs:
            return None
        port = self.inputs[port_name]
        return port.data if port.data is not None else port.default_value
    
    def set_output_data(self, port_name: str, data: Any):
        """Set data to output port"""
        if port_name in self.outputs:
            self.outputs[port_name].data = data

    def get_preview_outputs(self) -> Dict[str, Any]:
        """Return data exposed to the preview view.

        Most nodes preview their output ports. Terminal visualization nodes may
        override this method to expose cached preview-only data without adding a
        workflow output port.
        """
        return {
            port_name: port.data
            for port_name, port in self.outputs.items()
            if port.data is not None
        }
    
    def validate(self) -> Tuple[bool, str]:
        """
        Validate node configuration
        
        Returns:
            (is_valid, error_message)
        """
        # Check required input ports
        for name, port in self.inputs.items():
            if port.required and not port.is_connected and port.default_value is None:
                return False, tr_("Input port '{name}' is not connected").format(
                    name=port.display_name
                )
        
        # Validate parameters
        for name, value in self.parameter_values.items():
            if name in self.parameters:
                valid, msg = self.parameters[name].validate(value)
                if not valid:
                    return False, msg
        
        return True, ""
    
    @abstractmethod
    def execute(self) -> bool:
        """
        Execute node logic
        
        Subclasses must implement this method.
        Should read data from input ports, process it, and write to output ports.
        
        Returns:
            True for execution success, False for failure
        """
        pass
    
    def reset(self):
        """Reset node state"""
        self.state = NodeState.IDLE
        self.error_message = ""
        # Clear port data
        for port in self.inputs.values():
            port.clear()
        for port in self.outputs.values():
            port.clear()
        self.on_reset()

    def on_reset(self):
        """Hook for subclasses to clear internal runtime state."""
        pass
    
    def report_progress(self, progress: float, message: str = "", data: Dict = None):
        """
        Report node execution progress
        
        Args:
            progress: Progress value (0.0 ~ 1.0)
            message: Progress message
            data: Additional data (e.g., training metrics)
        """
        if self.progress_callback:
            self.progress_callback(progress, message, data or {})
    
    def report_status(self, message: str):
        """
        Report status message (displayed in status bar)
        
        Args:
            message: Status message
        """
        if self.status_callback:
            self.status_callback(message)
    
    def to_dict(self) -> Dict:
        """Serialize node to dictionary"""
        return {
            "id": self.node_id,
            "type": self.node_type,
            "position": list(self.position),
            "parameters": dict(self.parameter_values),
        }
    
    @classmethod
    def from_dict(cls, data: Dict) -> 'BaseNode':
        """Deserialize node from dictionary"""
        node = cls(node_id=data.get("id"))
        node.position = tuple(data.get("position", [0, 0]))
        for name, value in data.get("parameters", {}).items():
            node.set_parameter(name, value)
        return node
    
    def __repr__(self) -> str:
        return f"<{self.__class__.__name__}(id={self.node_id}, type={self.node_type})>"


# Node registry
_node_registry: Dict[str, Type[BaseNode]] = {}


def register_node(node_class: Type[BaseNode]) -> Type[BaseNode]:
    """
    Node registration decorator
    
    Usage:
        @register_node
        class MyNode(BaseNode):
            node_type = "my_node"
            ...
    """
    _node_registry[node_class.node_type] = node_class
    logger.debug(f"Registered node: {node_class.node_type} -> {node_class.__name__}")
    return node_class


def get_node_class(node_type: str) -> Optional[Type[BaseNode]]:
    """Get node class by type"""
    return _node_registry.get(node_type)


def get_all_node_types() -> List[str]:
    """Get all registered node types"""
    return list(_node_registry.keys())


def get_nodes_by_category(
    category: NodeCategory,
    include_hidden: bool = False,
) -> List[Type[BaseNode]]:
    """Get node classes for a category, excluding legacy nodes by default."""
    return [
        cls for cls in _node_registry.values()
        if cls.category == category
        and (include_hidden or getattr(cls, "visible_in_palette", True))
    ]


def create_node(node_type: str, node_id: str = None) -> Optional[BaseNode]:
    """Create node instance by type"""
    node_class = get_node_class(node_type)
    if node_class:
        return node_class(node_id=node_id)
    return None

