# -*- coding: utf-8 -*-
"""
Generic Graph Structure Base Classes

Provides unified graph structure abstractions for workflow nodes and model layers.

Architecture Notes
------------------
This module defines generic abstract classes for graph structures:
- `GraphNodeBase`: Graph node base class, provides common parameter management functionality
- `GraphBase`: Graph container base class, provides node/connection management and topology analysis
- `Connection`: Generic connection definition
- `create_registry`: Factory function to create node registries

Current Usage
-------------
- `BaseNode` (src/workflow/node_base.py): Workflow node base class, independent implementation
  - Added port system, execution state, progress callbacks and other workflow-specific features
  
- `LayerNode` (src/model_builder/layer_base.py): Model layer base class, independent implementation
  - Added Keras layer building, input/output shapes, weight status and other model-specific features

- `Workflow` (src/workflow/workflow.py): Workflow container, independent implementation
  - Uses Connection class from `workflow/connection.py` (with port information)
  
- `ModelGraph` (src/model_builder/model_graph.py): Model graph container, independent implementation
  - Uses `ModelConnection` class (model layer specific)

Design Decisions
----------------
Reasons why `BaseNode` and `LayerNode` don't directly inherit from `GraphNodeBase`:
1. Both have their own specific feature requirements (ports vs Keras layers)
2. Forced inheritance could lead to unnecessary API complexity
3. Current implementation is stable and feature-complete

Classes in this module can be used for:
1. Reference template for new graph structure implementations
2. Providing common graph algorithms (topological sort, connection management, etc.)
3. `create_registry()` factory function is actually used
"""

import logging
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Set, Tuple, Type

from .parameter import Parameter, ParamType


logger = logging.getLogger(__name__)


@dataclass
class Connection:
    """
    Generic connection definition
    
    Represents the connection relationship between two nodes in the graph.
    """
    source_id: str          # Source node ID
    target_id: str          # Target node ID
    source_port: str = ""   # Source port name (optional, for multi-port nodes)
    target_port: str = ""   # Target port name (optional)
    
    def to_dict(self) -> dict:
        """Serialize to dictionary"""
        data = {
            "source": self.source_id,
            "target": self.target_id,
        }
        if self.source_port:
            data["source_port"] = self.source_port
        if self.target_port:
            data["target_port"] = self.target_port
        return data
    
    @classmethod
    def from_dict(cls, data: dict) -> 'Connection':
        """Deserialize from dictionary"""
        return cls(
            source_id=data["source"],
            target_id=data["target"],
            source_port=data.get("source_port", ""),
            target_port=data.get("target_port", ""),
        )
    
    def __eq__(self, other):
        if not isinstance(other, Connection):
            return False
        return (self.source_id == other.source_id and 
                self.target_id == other.target_id and
                self.source_port == other.source_port and
                self.target_port == other.target_port)
    
    def __hash__(self):
        return hash((self.source_id, self.target_id, self.source_port, self.target_port))


class GraphNodeBase(ABC):
    """
    Graph node base class
    
    Provides common base functionality for BaseNode (workflow nodes) and LayerNode (model layers).
    Subclasses need to implement the _setup_parameters method.
    """
    
    # Class attributes - subclasses need to override
    node_type: str = "base"             # Node type identifier
    display_name: str = "Base Node"     # Display name
    description: str = ""               # Node description
    icon: str = "📦"                     # Node icon
    
    def __init__(self, node_id: str = None):
        """
        Initialize node
        
        Args:
            node_id: Node unique identifier, auto-generated by default
        """
        self.node_id = node_id or str(uuid.uuid4())[:8]
        self.parameters: Dict[str, Parameter] = {}
        self.parameter_values: Dict[str, Any] = {}
        
        # Initialize parameters
        self._setup_parameters()
        self._init_parameter_values()
    
    @abstractmethod
    def _setup_parameters(self):
        """
        Setup node parameters
        
        Subclasses must implement this method, using add_parameter to add parameters.
        """
        pass
    
    def _init_parameter_values(self):
        """Initialize parameter values to defaults"""
        for name, param in self.parameters.items():
            self.parameter_values[name] = param.default_value
    
    def add_parameter(
        self,
        name: str,
        param_type: ParamType,
        default_value: Any,
        display_name: str = None,
        description: str = "",
        min_value: Any = None,
        max_value: Any = None,
        choices: List[Any] = None,
        file_filter: str = "",
        required: bool = True
    ):
        """Add node parameter"""
        param = Parameter(
            name=name,
            display_name=display_name or name,
            param_type=param_type,
            default_value=default_value,
            description=description,
            min_value=min_value,
            max_value=max_value,
            choices=choices,
            file_filter=file_filter,
            required=required
        )
        self.parameters[name] = param
        self.parameter_values[name] = default_value
    
    def get_parameter(self, name: str) -> Any:
        """Get parameter value"""
        return self.parameter_values.get(name)
    
    def set_parameter(self, name: str, value: Any) -> Tuple[bool, str]:
        """
        Set parameter value
        
        Args:
            name: Parameter name
            value: Parameter value
            
        Returns:
            (success, error_message)
        """
        if name not in self.parameters:
            return False, f"Unknown parameter: {name}"
        
        param = self.parameters[name]
        valid, msg = param.validate(value)
        if not valid:
            return False, msg
        
        self.parameter_values[name] = value
        return True, ""
    
    def validate(self) -> Tuple[bool, str]:
        """
        Validate node configuration
        
        Returns:
            (is_valid, error_message)
        """
        for name, value in self.parameter_values.items():
            if name in self.parameters:
                valid, msg = self.parameters[name].validate(value)
                if not valid:
                    return False, msg
        return True, ""
    
    def to_dict(self) -> dict:
        """Serialize node to dictionary (base version, subclasses can extend)"""
        return {
            "id": self.node_id,
            "type": self.node_type,
            "parameters": dict(self.parameter_values),
        }
    
    @classmethod
    def from_dict(cls, data: dict) -> 'GraphNodeBase':
        """Deserialize node from dictionary"""
        node = cls(node_id=data.get("id"))
        for name, value in data.get("parameters", {}).items():
            node.set_parameter(name, value)
        return node
    
    def __repr__(self) -> str:
        return f"<{self.__class__.__name__}(id={self.node_id}, type={self.node_type})>"


class GraphBase(ABC):
    """
    Graph container base class
    
    Provides common graph management functionality for Workflow and ModelGraph.
    """
    
    def __init__(self, name: str = "Untitled"):
        self.name = name
        self.nodes: Dict[str, GraphNodeBase] = {}
        self.connections: List[Connection] = []
        self._dirty = False
    
    @property
    def is_dirty(self) -> bool:
        """Whether modified"""
        return self._dirty
    
    def _mark_dirty(self):
        """Mark as modified"""
        self._dirty = True
    
    def mark_saved(self):
        """Mark as saved"""
        self._dirty = False
    
    # ===== Node Management =====
    
    def add_node(self, node: GraphNodeBase) -> bool:
        """
        Add node
        
        Args:
            node: Node to add
            
        Returns:
            Whether addition was successful
        """
        if node.node_id in self.nodes:
            logger.warning(f"Node {node.node_id} already exists")
            return False
        
        self.nodes[node.node_id] = node
        self._mark_dirty()
        return True
    
    def remove_node(self, node_id: str) -> bool:
        """
        Remove node and all its connections
        
        Args:
            node_id: Node ID
            
        Returns:
            Whether removal was successful
        """
        if node_id not in self.nodes:
            return False
        
        # Remove related connections
        self.connections = [
            conn for conn in self.connections
            if conn.source_id != node_id and conn.target_id != node_id
        ]
        
        del self.nodes[node_id]
        self._mark_dirty()
        return True
    
    def get_node(self, node_id: str) -> Optional[GraphNodeBase]:
        """Get node"""
        return self.nodes.get(node_id)
    
    # ===== Connection Management =====
    
    def add_connection(self, connection: Connection) -> Tuple[bool, str]:
        """
        Add connection
        
        Args:
            connection: Connection object
            
        Returns:
            (success, error_message)
        """
        # Validate nodes exist
        if connection.source_id not in self.nodes:
            return False, f"Source node {connection.source_id} does not exist"
        if connection.target_id not in self.nodes:
            return False, f"Target node {connection.target_id} does not exist"
        
        # Check self-connection
        if connection.source_id == connection.target_id:
            return False, "Cannot self-connect"
        
        # Check if already exists
        if connection in self.connections:
            return False, "Connection already exists"
        
        self.connections.append(connection)
        self._mark_dirty()
        return True, ""
    
    def remove_connection(self, connection: Connection) -> bool:
        """Remove connection"""
        if connection not in self.connections:
            return False
        
        self.connections.remove(connection)
        self._mark_dirty()
        return True
    
    def connect(
        self,
        source_id: str,
        target_id: str,
        source_port: str = "",
        target_port: str = ""
    ) -> Tuple[bool, str]:
        """Convenience method to create connection"""
        connection = Connection(
            source_id=source_id,
            target_id=target_id,
            source_port=source_port,
            target_port=target_port
        )
        return self.add_connection(connection)
    
    def get_incoming_connections(self, node_id: str) -> List[Connection]:
        """Get all incoming connections for a node"""
        return [c for c in self.connections if c.target_id == node_id]
    
    def get_outgoing_connections(self, node_id: str) -> List[Connection]:
        """Get all outgoing connections for a node"""
        return [c for c in self.connections if c.source_id == node_id]
    
    # ===== Topology Analysis =====
    
    def get_execution_order(self) -> Tuple[List[str], bool]:
        """
        Get node execution order (topological sort)
        
        Uses Kahn's algorithm for topological sorting.
        
        Returns:
            (ordered_node_ids, has_cycle)
        """
        # Calculate in-degree for each node
        in_degree: Dict[str, int] = {node_id: 0 for node_id in self.nodes}
        for conn in self.connections:
            if conn.target_id in in_degree:
                in_degree[conn.target_id] += 1
        
        # Kahn's algorithm
        queue = [node_id for node_id, degree in in_degree.items() if degree == 0]
        result = []
        
        while queue:
            node_id = queue.pop(0)
            result.append(node_id)
            
            for conn in self.get_outgoing_connections(node_id):
                in_degree[conn.target_id] -= 1
                if in_degree[conn.target_id] == 0:
                    queue.append(conn.target_id)
        
        has_cycle = len(result) != len(self.nodes)
        return result, has_cycle
    
    def get_input_nodes(self) -> List[str]:
        """Get input nodes (nodes with no incoming connections)"""
        has_input = set(conn.target_id for conn in self.connections)
        return [nid for nid in self.nodes if nid not in has_input]
    
    def get_output_nodes(self) -> List[str]:
        """Get output nodes (nodes with no outgoing connections)"""
        has_output = set(conn.source_id for conn in self.connections)
        return [nid for nid in self.nodes if nid not in has_output]
    
    def get_upstream_nodes(self, node_id: str) -> Set[str]:
        """Get all upstream nodes for a specified node"""
        upstream = set()
        to_visit = [node_id]
        
        while to_visit:
            current = to_visit.pop()
            for conn in self.get_incoming_connections(current):
                if conn.source_id not in upstream:
                    upstream.add(conn.source_id)
                    to_visit.append(conn.source_id)
        
        return upstream
    
    def get_downstream_nodes(self, node_id: str) -> Set[str]:
        """Get all downstream nodes for a specified node"""
        downstream = set()
        to_visit = [node_id]
        
        while to_visit:
            current = to_visit.pop()
            for conn in self.get_outgoing_connections(current):
                if conn.target_id not in downstream:
                    downstream.add(conn.target_id)
                    to_visit.append(conn.target_id)
        
        return downstream
    
    def validate(self) -> Tuple[bool, List[str]]:
        """
        Validate graph structure
        
        Returns:
            (is_valid, error_messages)
        """
        errors = []
        
        if not self.nodes:
            errors.append("图为空")
        
        # Validate each node
        for node in self.nodes.values():
            valid, msg = node.validate()
            if not valid:
                errors.append(f"节点 '{node.display_name}' ({node.node_id}): {msg}")
        
        # Check for cycles
        _, has_cycle = self.get_execution_order()
        if has_cycle:
            errors.append("存在循环依赖")
        
        return len(errors) == 0, errors
    
    def to_dict(self) -> dict:
        """Serialize graph to dictionary (base version, subclasses can extend)"""
        return {
            "name": self.name,
            "nodes": [node.to_dict() for node in self.nodes.values()],
            "connections": [conn.to_dict() for conn in self.connections],
        }
    
    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name='{self.name}', nodes={len(self.nodes)}, connections={len(self.connections)})"


# ===== Registry Utility Functions =====

def create_registry():
    """
    Create node/layer registry
    
    Returns:
        (registry_dict, register_decorator, get_class_func, create_instance_func)
    
    Usage example:
        _registry, register_node, get_node_class, create_node = create_registry()
        
        @register_node
        class MyNode(BaseNode):
            node_type = "my_node"
    """
    registry: Dict[str, Type[GraphNodeBase]] = {}
    
    def register(cls: Type[GraphNodeBase]) -> Type[GraphNodeBase]:
        """Register decorator"""
        registry[cls.node_type] = cls
        logger.debug(f"Registered: {cls.node_type} -> {cls.__name__}")
        return cls
    
    def get_class(node_type: str) -> Optional[Type[GraphNodeBase]]:
        """Get class by type"""
        return registry.get(node_type)
    
    def create_instance(node_type: str, node_id: str = None) -> Optional[GraphNodeBase]:
        """Create instance by type"""
        cls = get_class(node_type)
        if cls:
            return cls(node_id=node_id)
        return None
    
    def get_all_types() -> List[str]:
        """Get all registered types"""
        return list(registry.keys())
    
    return registry, register, get_class, create_instance, get_all_types


